spring.application.name=backend

# ==============================
# Threads API
# ==============================

threads.api.base-url=https://graph.threads.net/v1.0

# Threads Access Token
threads.access-token=THAAPCirbpuXBBYmFXM19FRDFRa21IaWdYZAWFkNHB3S1AyRmVseWJINHp4NmxrWHpjaDU2Y2ZAHR3ZAMQzh6cWFWeGQxTFM5YmtKUnBEWHJBdlZA3MnlxNElhMkZAIN0E0VlVjTHZAFc1Juc0R0ZAHJEWnZAHTlNHTTQ2RDBjNkVtdHdZAM0phbjdaTGFMOHRlcWg1OGQ5NDFHVlpQSjlMVXRaYzF6ZAHNBenQZD

# Thread ID cần lấy comment
threads.thread-id=18459302773143925